index:
    path: /
    controller: App\Controller\DefaultController::index

about-us:
    path: /about-us
    controller: App\Controller\DefaultController::index

articles:
    path: /articles/
    controller: App\Controller\ArticlesController::index

articles_categorie:
    path: /articles/{slug}
    controller: App\Controller\ArticlesController::indexByCategorie